version: '3.7'
services:
    db:
        image: postgres:latest
        restart: always
        ports:
            - 5432:5432
        environment: 
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql
            - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
