CREATE ROLE db_user WITH NOINHERIT LOGIN PASSWORD 'db_pass';

CREATE DATABASE db OWNER db_user;

\connect db;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO db_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO db_user;